apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-dpfysqdn
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-dpfysqdn:fa920da05446faddf40822915b8f75e3f1e89db6@sha256:3531b151b347eed32025e925236523c4923bc23294dc3ddfb633f350195d05dc
        name: container-image  
